theme: jekyll-theme-minimal
title: "InstaBot by Micha Birklbauer"
description: "Project Website for InstaBot"
logo: https://raw.githubusercontent.com/michabirklbauer/michabirklbauer.github.io/master/avatar.jpg
show_downloads: "true"
github:
  zip_url: https://github.com/michabirklbauer/instagram_watchdog/archive/master.zip
  tar_url: https://github.com/michabirklbauer/instagram_watchdog/archive/master.tar.gz
